[package]
name = "image-fnb"
version = "1.0.0"
edition = "2021"
description = "Wrapper around image-rs for use in fnb"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "debuginfo"

[dependencies]
image = "0.25.5"
libc = "0.2.168"
